// Helper function to create icon object with accessibility properties
const createIcon = (key: string, url: string) => ({
    url,
    alt: `${key.charAt(0).toUpperCase() + key.slice(1)} icon`,
    ariaLabel: `${key.charAt(0).toUpperCase() + key.slice(1)} icon`
});

// Helper function to create icon with custom alt text and aria-label
const createIconCustom = (_key: string, url: string, altText: string, ariaLabel: string) => ({
    url,
    alt: altText,
    ariaLabel: ariaLabel
});

export const icons = {
    python: createIcon('python', `${import.meta.env.VITE_CLOUDFRONT_URL}/languages/python.svg`),
    react: createIcon('react', `${import.meta.env.VITE_CLOUDFRONT_URL}/frameworks/react.svg`),
    vue: createIcon('vue', `${import.meta.env.VITE_CLOUDFRONT_URL}/frameworks/vue.svg`),
    node: createIcon('node', `${import.meta.env.VITE_CLOUDFRONT_URL}/frameworks/node.svg`),
    express: createIcon('express', `${import.meta.env.VITE_CLOUDFRONT_URL}/frameworks/express.svg`),
    nestjs: createIcon('nestjs', `${import.meta.env.VITE_CLOUDFRONT_URL}/frameworks/nest.svg`),
    docker: createIcon('docker', `${import.meta.env.VITE_CLOUDFRONT_URL}/docker.svg`),
    kubernetes: createIcon('kubernetes', `${import.meta.env.VITE_CLOUDFRONT_URL}/k8.svg`),
    apiGateway: createIconCustom('apiGateway', `${import.meta.env.VITE_CLOUDFRONT_URL}/aws/api-gateway.svg`, 'API Gateway icon', 'AWS API Gateway service'),
    s3: createIconCustom('s3', `${import.meta.env.VITE_CLOUDFRONT_URL}/aws/s3.svg`, 'S3 icon', 'AWS S3 storage service'),
    cloudfront: createIconCustom('cloudfront', `${import.meta.env.VITE_CLOUDFRONT_URL}/aws/cloudfront.svg`, 'CloudFront icon', 'AWS CloudFront CDN service'),
    cloudformation: createIconCustom('cloudformation', `${import.meta.env.VITE_CLOUDFRONT_URL}/aws/cloudformation.svg`, 'CloudFormation icon', 'AWS CloudFormation infrastructure as code'),
    documentdb: createIconCustom('documentdb', `${import.meta.env.VITE_CLOUDFRONT_URL}/aws/documentdb.svg`, 'DocumentDB icon', 'AWS DocumentDB database service'),
    dynamodb: createIconCustom('dynamodb', `${import.meta.env.VITE_CLOUDFRONT_URL}/aws/dynamodb.svg`, 'DynamoDB icon', 'AWS DynamoDB NoSQL database'),
    lambda: createIconCustom('lambda', `${import.meta.env.VITE_CLOUDFRONT_URL}/aws/lambda.svg`, 'Lambda icon', 'AWS Lambda serverless function'),
    rds: createIconCustom('rds', `${import.meta.env.VITE_CLOUDFRONT_URL}/aws/rds.svg`, 'RDS icon', 'AWS RDS relational database service'),
    redshift: createIconCustom('redshift', `${import.meta.env.VITE_CLOUDFRONT_URL}/aws/redshift.svg`, 'Redshift icon', 'AWS Redshift data warehouse'),
    sns: createIconCustom('sns', `${import.meta.env.VITE_CLOUDFRONT_URL}/aws/sns.svg`, 'SNS icon', 'AWS SNS notification service'),
    sqs: createIconCustom('sqs', `${import.meta.env.VITE_CLOUDFRONT_URL}/aws/sqs.svg`, 'SQS icon', 'AWS SQS message queue service'),
    efs: createIconCustom('efs', `${import.meta.env.VITE_CLOUDFRONT_URL}/aws/efs.svg`, 'EFS icon', 'AWS EFS file system service'),
    ec2: createIconCustom('ec2', `${import.meta.env.VITE_CLOUDFRONT_URL}/aws/ec2.svg`, 'EC2 icon', 'AWS EC2 compute service'),
    ecs: createIconCustom('ecs', `${import.meta.env.VITE_CLOUDFRONT_URL}/aws/ecs.svg`, 'ECS icon', 'AWS ECS container service'),
    fargate: createIconCustom('fargate', `${import.meta.env.VITE_CLOUDFRONT_URL}/aws/fargate.svg`, 'Fargate icon', 'AWS Fargate serverless containers'),
    iam: createIconCustom('iam', `${import.meta.env.VITE_CLOUDFRONT_URL}/aws/iam.svg`, 'IAM icon', 'AWS IAM identity and access management'),
    sagemaker: createIconCustom('sagemaker', `${import.meta.env.VITE_CLOUDFRONT_URL}/aws/sagemaker.svg`, 'SageMaker icon', 'AWS SageMaker machine learning platform'),
    secretsManager: createIconCustom('secretsManager', `${import.meta.env.VITE_CLOUDFRONT_URL}/aws/secretsmanager.svg`, 'Secrets Manager icon', 'AWS Secrets Manager service'),
    ebs: createIconCustom('ebs', `${import.meta.env.VITE_CLOUDFRONT_URL}/aws/ebs.svg`, 'EBS icon', 'AWS EBS block storage service'),
    couchbase: createIcon('couchbase', `${import.meta.env.VITE_CLOUDFRONT_URL}/couchbase.svg`),
    cypress: createIcon('cypress', `${import.meta.env.VITE_CLOUDFRONT_URL}/cypress.svg`),
    playwright: createIcon('playwright', `${import.meta.env.VITE_CLOUDFRONT_URL}/playwright.svg`),
    figma: createIcon('figma', `${import.meta.env.VITE_CLOUDFRONT_URL}/figma.svg`),
    git: createIcon('git', `${import.meta.env.VITE_CLOUDFRONT_URL}/git.svg`),
    github: createIcon('github', `${import.meta.env.VITE_CLOUDFRONT_URL}/github.svg`),
    gitlab: createIcon('gitlab', `${import.meta.env.VITE_CLOUDFRONT_URL}/gitlab.svg`),
    k6: createIcon('k6', `${import.meta.env.VITE_CLOUDFRONT_URL}/k6.svg`),
    mongodb: createIconCustom('mongodb', `${import.meta.env.VITE_CLOUDFRONT_URL}/mongodb.svg`, 'MongoDB icon', 'MongoDB database'),
    mysql: createIcon('mysql', `${import.meta.env.VITE_CLOUDFRONT_URL}/mysql.svg`),
    nginx: createIcon('nginx', `${import.meta.env.VITE_CLOUDFRONT_URL}/nginx.svg`),
    postgres: createIconCustom('postgres', `${import.meta.env.VITE_CLOUDFRONT_URL}/postgres.svg`, 'PostgreSQL icon', 'PostgreSQL database'),
    rabbitmq: createIcon('rabbitmq', `${import.meta.env.VITE_CLOUDFRONT_URL}/rabbitmq.svg`),
    memcached: createIcon('memcached', `${import.meta.env.VITE_CLOUDFRONT_URL}/memcached.svg`),
    redis: createIcon('redis', `${import.meta.env.VITE_CLOUDFRONT_URL}/redis.svg`),
    graphql: createIcon('graphql', `${import.meta.env.VITE_CLOUDFRONT_URL}/graphql.svg`),
    swagger: createIcon('swagger', `${import.meta.env.VITE_CLOUDFRONT_URL}/swagger.svg`),

    pubsub: createIconCustom('pubsub', `${import.meta.env.VITE_CLOUDFRONT_URL}/gcs/pubsub.svg`, 'Pub/Sub icon', 'Google Cloud Pub/Sub messaging'),
    postman: createIcon('postman', `${import.meta.env.VITE_CLOUDFRONT_URL}/postman.svg`),
    prometheus: createIcon('prometheus', `${import.meta.env.VITE_CLOUDFRONT_URL}/prometheus.svg`),
    jenkins: createIcon('jenkins', `${import.meta.env.VITE_CLOUDFRONT_URL}/jenkins.svg`),
    jest: createIcon('jest', `${import.meta.env.VITE_CLOUDFRONT_URL}/jest.svg`),
    jmeter: createIcon('jmeter', `${import.meta.env.VITE_CLOUDFRONT_URL}/jmeter.svg`),
    kafka: createIcon('kafka', `${import.meta.env.VITE_CLOUDFRONT_URL}/kafka.svg`),
    terraform: createIcon('terraform', `${import.meta.env.VITE_CLOUDFRONT_URL}/terraform.svg`),
    xamarin: createIcon('xamarin', `${import.meta.env.VITE_CLOUDFRONT_URL}/xamarin.svg`),
    azureDevops: createIconCustom('azureDevops', `${import.meta.env.VITE_CLOUDFRONT_URL}/azure/azuredevops.svg`, 'Azure DevOps icon', 'Azure DevOps platform'),
    azureServiceBus: createIconCustom('azureServiceBus', `${import.meta.env.VITE_CLOUDFRONT_URL}/azure/service-bus.svg`, 'Azure Service Bus icon', 'Azure Service Bus messaging'),
    ansible: createIcon('ansible', `${import.meta.env.VITE_CLOUDFRONT_URL}/ansible.svg`),
    kotlin: createIcon('kotlin', `${import.meta.env.VITE_CLOUDFRONT_URL}/kotlin.svg`),
    swift: createIcon('swift', `${import.meta.env.VITE_CLOUDFRONT_URL}/swift.svg`),
    swiftui: createIcon('swiftui', `${import.meta.env.VITE_CLOUDFRONT_URL}/swiftui.svg`),
    dart: createIcon('dart', `${import.meta.env.VITE_CLOUDFRONT_URL}/languages/dart.svg`),
    flutter: createIcon('flutter', `${import.meta.env.VITE_CLOUDFRONT_URL}/frameworks/flutter.svg`),
    reactNative: createIconCustom('reactNative', `${import.meta.env.VITE_CLOUDFRONT_URL}/react-native.svg`, 'React Native icon', 'React Native mobile framework'),
    svelte: createIcon('svelte', `${import.meta.env.VITE_CLOUDFRONT_URL}/languages/svelte.svg`),
    tailwind: createIconCustom('tailwind', `${import.meta.env.VITE_CLOUDFRONT_URL}/tailwindcss.svg`, 'Tailwind CSS icon', 'Tailwind CSS framework'),
    typescript: createIcon('typescript', `${import.meta.env.VITE_CLOUDFRONT_URL}/typescript.svg`),
    java: createIcon('java', `${import.meta.env.VITE_CLOUDFRONT_URL}/languages/java.svg`),
    helm: createIcon('helm', `${import.meta.env.VITE_CLOUDFRONT_URL}/helm.svg`),
    go: createIcon('go', `${import.meta.env.VITE_CLOUDFRONT_URL}/languages/go.svg`),
    rust: createIcon('rust', `${import.meta.env.VITE_CLOUDFRONT_URL}/languages/rust.svg`),
    numpy: createIcon('numpy', `${import.meta.env.VITE_CLOUDFRONT_URL}/data-science/numpy.svg`),
    matplotlib: createIcon('matplotlib', `${import.meta.env.VITE_CLOUDFRONT_URL}/data-science/matplotlib.svg`),
    pandas: createIcon('pandas', `${import.meta.env.VITE_CLOUDFRONT_URL}/data-science/pandas.svg`),
    scikitLearn: createIconCustom('scikitLearn', `${import.meta.env.VITE_CLOUDFRONT_URL}/data-science/scikit-learn.svg`, 'Scikit-learn icon', 'Scikit-learn machine learning library'),
    tensorflow: createIcon('tensorflow', `${import.meta.env.VITE_CLOUDFRONT_URL}/data-science/tensorflow.svg`),
    pytorch: createIcon('pytorch', `${import.meta.env.VITE_CLOUDFRONT_URL}/data-science/pytorch.svg`),
    scipy: createIcon('scipy', `${import.meta.env.VITE_CLOUDFRONT_URL}/data-science/scipy.svg`),
    seaborn: createIcon('seaborn', `${import.meta.env.VITE_CLOUDFRONT_URL}/data-science/seaborn.svg`),
    xgboost: createIcon('xgboost', `${import.meta.env.VITE_CLOUDFRONT_URL}/xgboost.svg`),
    plotly: createIcon('plotly', `${import.meta.env.VITE_CLOUDFRONT_URL}/data-science/plotly.svg`),
    django: createIcon('django', `${import.meta.env.VITE_CLOUDFRONT_URL}/frameworks/django.svg`),
    fastapi: createIconCustom('fastapi', `${import.meta.env.VITE_CLOUDFRONT_URL}/frameworks/fastapi.svg`, 'FastAPI icon', 'FastAPI Python web framework'),
    angular: createIcon('angular', `${import.meta.env.VITE_CLOUDFRONT_URL}/frameworks/angular.svg`),
    nest: createIcon('nest', `${import.meta.env.VITE_CLOUDFRONT_URL}/frameworks/nest.svg`),
    nodejs: createIconCustom('node.js', `${import.meta.env.VITE_CLOUDFRONT_URL}/frameworks/nodejs.svg`, 'Node.js icon', 'Node.js JavaScript runtime'),
    vite: createIcon('vite', `${import.meta.env.VITE_CLOUDFRONT_URL}/frameworks/vite.svg`),
    airflow: createIcon('airflow', `${import.meta.env.VITE_CLOUDFRONT_URL}/apacheairflow.svg`),
    echo: createIcon('echo', `${import.meta.env.VITE_CLOUDFRONT_URL}/frameworks/echo.png`),
    jetpackcompose: createIcon('jetpackcompose', `${import.meta.env.VITE_CLOUDFRONT_URL}/jetpackcompose.svg`),
    dvc: createIcon('dvc', `${import.meta.env.VITE_CLOUDFRONT_URL}/dvc.svg`),

    // Additional missing icons from technology patterns
    // Programming Languages & Frameworks
    spring: createIcon('spring', `${import.meta.env.VITE_CLOUDFRONT_URL}/frameworks/spring.svg`),
    scala: createIcon('scala', `${import.meta.env.VITE_CLOUDFRONT_URL}/languages/scala.svg`),
    android: createIcon('android', `${import.meta.env.VITE_CLOUDFRONT_URL}/android.svg`),
    
    // Cloud & Infrastructure
    apigee: createIconCustom('apigee', `${import.meta.env.VITE_CLOUDFRONT_URL}/apigee.svg`, 'Apigee icon', 'Google Apigee API management'),
    appengine: createIconCustom('appengine', `${import.meta.env.VITE_CLOUDFRONT_URL}/gcs/appengine.svg`, 'App Engine icon', 'Google App Engine'),
    appservice: createIconCustom('appservice', `${import.meta.env.VITE_CLOUDFRONT_URL}/azure/appservice.svg`, 'App Service icon', 'Azure App Service'),
    argoCD: createIconCustom('argoCD', `${import.meta.env.VITE_CLOUDFRONT_URL}/argocd.svg`, 'ArgoCD icon', 'ArgoCD GitOps continuous delivery'),
    astro: createIcon('astro', `${import.meta.env.VITE_CLOUDFRONT_URL}/astrojs.svg`),
    azuresql: createIconCustom('azuresql', `${import.meta.env.VITE_CLOUDFRONT_URL}/azure/azuresql.svg`, 'Azure SQL icon', 'Azure SQL Database'),
    cosmosdb: createIconCustom('cosmosdb', `${import.meta.env.VITE_CLOUDFRONT_URL}/azure/cosmosdb.svg`, 'CosmosDB icon', 'Azure CosmosDB database'),
    bigquery: createIconCustom('bigquery', `${import.meta.env.VITE_CLOUDFRONT_URL}/gcs/bigquery.svg`, 'BigQuery icon', 'Google BigQuery data warehouse'),
    consul: createIcon('consul', `${import.meta.env.VITE_CLOUDFRONT_URL}/consul.svg`),
    dagster: createIcon('dagster', `${import.meta.env.VITE_CLOUDFRONT_URL}/dagster.svg`),
    deltaLake: createIconCustom('deltaLake', `${import.meta.env.VITE_CLOUDFRONT_URL}/delta-lake.png`, 'Delta Lake icon', 'Delta Lake data lake storage'),
    feast: createIcon('feast', `${import.meta.env.VITE_CLOUDFRONT_URL}/feast.svg`),
    firestore: createIconCustom('firestore', `${import.meta.env.VITE_CLOUDFRONT_URL}/firestore.svg`, 'Firestore icon', 'Google Firestore database'),
    flink: createIcon('flink', `${import.meta.env.VITE_CLOUDFRONT_URL}/flink.svg`),
    flyway: createIcon('flyway', `${import.meta.env.VITE_CLOUDFRONT_URL}/flyway.svg`),
    gin: createIcon('gin', `${import.meta.env.VITE_CLOUDFRONT_URL}/gin.svg`),
    grpc: createIcon('grpc', `${import.meta.env.VITE_CLOUDFRONT_URL}/grpc.png`),
    iceberg: createIcon('iceberg', `${import.meta.env.VITE_CLOUDFRONT_URL}/iceberg.svg`),
    jax: createIcon('jax', `${import.meta.env.VITE_CLOUDFRONT_URL}/jax.svg`),
    jotai: createIcon('jotai', `${import.meta.env.VITE_CLOUDFRONT_URL}/jotai.png`),
    kibana: createIcon('kibana', `${import.meta.env.VITE_CLOUDFRONT_URL}/kibana.svg`),
    kubeflow: createIcon('kubeflow', `${import.meta.env.VITE_CLOUDFRONT_URL}/kubeflow.svg`),
    langchain: createIcon('langchain', `${import.meta.env.VITE_CLOUDFRONT_URL}/langchain.svg`),
    lightGBM: createIconCustom('lightGBM', `${import.meta.env.VITE_CLOUDFRONT_URL}/lightgbm.svg`, 'LightGBM icon', 'LightGBM gradient boosting framework'),
    llamaindex: createIcon('llamaindex', `${import.meta.env.VITE_CLOUDFRONT_URL}/llamaindex.svg`),
    logstash: createIcon('logstash', `${import.meta.env.VITE_CLOUDFRONT_URL}/logstash.svg`),
    materialUi: createIconCustom('materialUi', `${import.meta.env.VITE_CLOUDFRONT_URL}/material-ui.svg`, 'Material-UI icon', 'Material-UI React component library'),
    mobx: createIcon('mobx', `${import.meta.env.VITE_CLOUDFRONT_URL}/mobx.svg`),
    neo4j: createIcon('neo4j', `${import.meta.env.VITE_CLOUDFRONT_URL}/neo4j.svg`),
    ngrx: createIcon('ngrx', `${import.meta.env.VITE_CLOUDFRONT_URL}/ngrx.svg`),
    ngxs: createIcon('ngxs', `${import.meta.env.VITE_CLOUDFRONT_URL}/ngxs.png`),
    nuxt: createIcon('nuxt', `${import.meta.env.VITE_CLOUDFRONT_URL}/frameworks/nuxt.svg`),
    pinia: createIcon('pinia', `${import.meta.env.VITE_CLOUDFRONT_URL}/pinia.svg`),
    prefect: createIcon('prefect', `${import.meta.env.VITE_CLOUDFRONT_URL}/prefect.svg`),
    redux: createIcon('redux', `${import.meta.env.VITE_CLOUDFRONT_URL}/redux.svg`),
    sass: createIcon('sass', `${import.meta.env.VITE_CLOUDFRONT_URL}/sass.svg`),
    splunk: createIcon('splunk', `${import.meta.env.VITE_CLOUDFRONT_URL}/splunk.svg`),
    tecton: createIcon('tecton', `${import.meta.env.VITE_CLOUDFRONT_URL}/tecton.svg`),
    teradata: createIcon('teradata', `${import.meta.env.VITE_CLOUDFRONT_URL}/teradata.svg`),
    uikit: createIcon('uikit', `${import.meta.env.VITE_CLOUDFRONT_URL}/uikit.svg`),
    vuex: createIcon('vuex', `${import.meta.env.VITE_CLOUDFRONT_URL}/vuex.svg`),
    xml: createIcon('xml', `${import.meta.env.VITE_CLOUDFRONT_URL}/xml.svg`),
    zustand: createIcon('zustand', `${import.meta.env.VITE_CLOUDFRONT_URL}/zustand.svg`),
    less: createIcon('less', `${import.meta.env.VITE_CLOUDFRONT_URL}/less.svg`),
    nextjs: createIcon('nextjs', `${import.meta.env.VITE_CLOUDFRONT_URL}/nextjs.svg`),
    remix: createIcon('remix', `${import.meta.env.VITE_CLOUDFRONT_URL}/remix.svg`),
    gatsby: createIcon('gatsby', `${import.meta.env.VITE_CLOUDFRONT_URL}/gatsby.svg`),
    antDesign: createIcon('antDesign', `${import.meta.env.VITE_CLOUDFRONT_URL}/ant-design.svg`),
    aws: createIcon('aws', `${import.meta.env.VITE_CLOUDFRONT_URL}/aws/aws.svg`),
    dbt: createIcon('dbt', `${import.meta.env.VITE_CLOUDFRONT_URL}/dbt.svg`),
    hashicorpVault: createIcon('hashicorpVault', `${import.meta.env.VITE_CLOUDFRONT_URL}/hashicorp-vault.svg`),
    kong: createIcon('kong', `${import.meta.env.VITE_CLOUDFRONT_URL}/kong.svg`),
    
    // Testing & Tools
    selenium: createIcon('selenium', `${import.meta.env.VITE_CLOUDFRONT_URL}/selenium.svg`),
    grafana: createIcon('grafana', `${import.meta.env.VITE_CLOUDFRONT_URL}/grafana.svg`),
    jaeger: createIcon('jaeger', `${import.meta.env.VITE_CLOUDFRONT_URL}/jaeger.svg`),
    zipkin: createIcon('zipkin', `${import.meta.env.VITE_CLOUDFRONT_URL}/zipkin.svg`),
    circleci: createIcon('circleci', `${import.meta.env.VITE_CLOUDFRONT_URL}/circleci.svg`),
    travisci: createIcon('travisci', `${import.meta.env.VITE_CLOUDFRONT_URL}/travisci.svg`),
    sketch: createIcon('sketch', `${import.meta.env.VITE_CLOUDFRONT_URL}/sketch.svg`),
    adobeXd: createIconCustom('adobeXd', `${import.meta.env.VITE_CLOUDFRONT_URL}/adobexd.svg`, 'Adobe XD icon', 'Adobe XD design tool'),
    elasticsearch: createIcon('elasticsearch', `${import.meta.env.VITE_CLOUDFRONT_URL}/elasticsearch.svg`),
    mlflow: createIcon('mlflow', `${import.meta.env.VITE_CLOUDFRONT_URL}/mlflow.svg`),
    
    // Big Data & Analytics
    hadoop: createIcon('hadoop', `${import.meta.env.VITE_CLOUDFRONT_URL}/apachehadoop.svg`),
    spark: createIcon('spark', `${import.meta.env.VITE_CLOUDFRONT_URL}/apachespark.svg`),
    chaosMonkey: createIconCustom('chaosMonkey', `${import.meta.env.VITE_CLOUDFRONT_URL}/chaosmonkey.svg`, 'Chaos Monkey icon', 'Netflix Chaos Monkey resilience testing'),
    flask: createIcon('flask', `${import.meta.env.VITE_CLOUDFRONT_URL}/frameworks/flask.svg`),
    flux: createIcon('flux', `${import.meta.env.VITE_CLOUDFRONT_URL}/flux.svg`),
    googlecloudfunctions: createIcon('googleCloudFunctions', `${import.meta.env.VITE_CLOUDFRONT_URL}/gcs/google-cloud-functions.svg`),
    pulumi: createIcon('pulumi', `${import.meta.env.VITE_CLOUDFRONT_URL}/pulumi.svg`),
    snowflake: createIcon('snowflake', `${import.meta.env.VITE_CLOUDFRONT_URL}/snowflake.svg`),
    hf: createIcon('hf', `${import.meta.env.VITE_CLOUDFRONT_URL}/hf.svg`),

    dedenne: createIcon('dedenne', `${import.meta.env.VITE_CLOUDFRONT_URL}/dedenne.png`),
}