/**
 * Technology detection patterns for identifying technologies mentioned in question text.
 * These patterns are used to automatically detect and display relevant technology icons.
 */

export const technologyPatterns = {
  // Programming Languages
  'python': /\b(python)\b/i,
  'nodejs': /\b(node\.?js|nodejs)\b/i,
  'typescript': /\b(typescript|ts)\b/i,
  'java': /\b(java)\b/i,
  'go': /\b(go|golang)\b/i,
  'rust': /\b(rust)\b/i,
  'swift': /\b(swift)\b/i,
  'kotlin': /\b(kotlin)\b/i,
  'dart': /\b(dart)\b/i,
  'swiftui': /\b(swiftui)\b/i,
  'jetpackcompose': /\b(jetpack compose)\b/i,
  
  // Frameworks & Libraries
  'react': /\b(react)\b/i,
  'vue': /\b(vue)\b/i,
  'angular': /\b(angular)\b/i,
  'svelte': /\b(svelte)\b/i,
  'express': /\b(express)\b/i,
  'django': /\b(django)\b/i,
  'fastapi': /\b(fastapi)\b/i,
  'tailwind': /\b(tailwind|tailwind css)\b/i,
  'graphql': /\b(graphql)\b/i,
  'flask': /\b(flask)\b/i,
  'nestjs': /\b(nestjs)\b/i,
  
  // Databases
  'mongodb': /\b(mongodb|mongo)\b/i,
  'mysql': /\b(mysql)\b/i,
  'postgres': /\b(postgresql|postgres)\b/i,
  'dynamodb': /\b(dynamodb)\b/i,
  'couchbase': /\b(couchbase)\b/i,
  'redis': /\b(redis)\b/i,
  'memcached': /\b(memcached)\b/i,
  
  // Cloud & Infrastructure
  'docker': /\b(docker|dockerfile)\b/i,
  'kubernetes': /\b(kubernetes|k8s)\b/i,
  'helm': /\b(helm)\b/i,
  'terraform': /\b(terraform)\b/i,
  'ansible': /\b(ansible)\b/i,
  'ec2': /\b(ec2)\b/i,
  'ecs': /\b(ecs)\b/i,
  'eks': /\b(eks)\b/i,
  'fargate': /\b(fargate)\b/i,
  'iam': /\b(iam)\b/i,
  'sagemaker': /\b(sagemaker)\b/i,
  'secretsManager': /\b(secrets\s*manager)\b/i,
  'ebs': /\b(ebs)\b/i,
  'apiGateway': /\b(api\s*gateway|apigateway)\b/i,
  's3': /\b(s3)\b/i,
  'cloudfront': /\b(cloudfront)\b/i,
  'cloudformation': /\b(cloudformation)\b/i,
  'documentdb': /\b(documentdb)\b/i,
  'rds': /\b(rds)\b/i,
  'redshift': /\b(redshift)\b/i,
  'sns': /\b(sns)\b/i,
  'sqs': /\b(sqs)\b/i,
  'efs': /\b(efs)\b/i,
  'lambda': /\b(lambda)\b/i,
  'azureDevops': /\b(azure devops)\b/i,
  'azureServiceBus': /\b(azure service bus)\b/i,
  'azurefunctions': /\b(azure functions)\b/i,
  'azureappservice': /\b(azure app service)\b/i,
  'snowflake': /\b(snowflake)\b/i,
  
  // Testing
  'jest': /\b(jest)\b/i,
  'cypress': /\b(cypress)\b/i,
  'playwright': /\b(playwright)\b/i,
  'selenium': /\b(selenium)\b/i,
  'jmeter': /\b(jmeter)\b/i,
  'k6': /\b(k6)\b/i,
  'hashicorpVault': /\b(hashicorp vault)\b/i,
  'kong': /\b(kong)\b/i,
  'dvc': /\b(dvc)\b/i,
  
  // Tools & Services
  'git': /\b(git)\b/i,
  'github': /\b(github)\b/i,
  'gitlab': /\b(gitlab)\b/i,
  'jenkins': /\b(jenkins)\b/i,
  'circleci': /\b(circleci)\b/i,
  'prometheus': /\b(prometheus)\b/i,
  'grafana': /\b(grafana)\b/i,
  'jaeger': /\b(jaeger)\b/i,
  'zipkin': /\b(zipkin)\b/i,
  'kafka': /\b(kafka)\b/i,
  'rabbitmq': /\b(rabbitmq)\b/i,
  'pubsub': /\b(pub\/sub|google pub\/sub)\b/i,
  'postman': /\b(postman)\b/i,
  'figma': /\b(figma)\b/i,
  'sketch': /\b(sketch)\b/i,
  'adobeXd': /\b(adobe xd)\b/i,
  'nginx': /\b(nginx)\b/i,
  'vite': /\b(vite)\b/i,
  'webpack': /\b(webpack)\b/i,
  'babel': /\b(babel)\b/i,
  'reactNative': /\b(react native)\b/i,
  'xamarin': /\b(xamarin)\b/i,
  'flutter': /\b(flutter)\b/i,
  'openapi': /\b(openapi)\b/i,
  'swagger': /\b(swagger)\b/i,
  
  // Data Science & ML
  'numpy': /\b(numpy)\b/i,
  'pandas': /\b(pandas)\b/i,
  'matplotlib': /\b(matplotlib)\b/i,
  'seaborn': /\b(seaborn)\b/i,
  'plotly': /\b(plotly)\b/i,
  'scikitLearn': /\b(scikit-learn|scikit learn)\b/i,
  'tensorflow': /\b(tensorflow)\b/i,
  'pytorch': /\b(pytorch)\b/i,
  'xgboost': /\b(xgboost)\b/i,
  'scipy': /\b(scipy)\b/i,
  'mlflow': /\b(mlflow)\b/i,
  'kubeflow': /\b(kubeflow)\b/i,

  // Additional Technologies
  'android': /\b(android)\b/i,
  'airflow': /\b(airflow)\b/i,
  'hadoop': /\b(hadoop)\b/i,
  'spark': /\b(spark)\b/i,
  'apigee': /\b(apigee)\b/i,
  'appengine': /\b(app engine)\b/i,
  'appservice': /\b(appservice)\b/i,
  'argoCD': /\b(argo cd)\b/i,
  'astro': /\b(astro)\b/i,
  'azuresql': /\b(azure sql)\b/i,
  'cosmosdb': /\b(cosmosdb)\b/i,
  'bigquery': /\b(bigquery)\b/i,
  'chaosMonkey': /\b(chaos monkey)\b/i,
  'consul': /\b(consul)\b/i,
  'dagster': /\b(dagster)\b/i,
  'deltaLake': /\b(delta lake)\b/i,
  'feast': /\b(feast)\b/i,
  'firestore': /\b(firestore)\b/i,
  'flink': /\b(flink)\b/i,
  'flyway': /\b(flyway)\b/i,
  'gin': /\b(gin)\b/i,
  'grpc': /\b(grpc)\b/i,
  'iceberg': /\b(iceberg)\b/i,
  'jax': /\b(jax)\b/i,
  'jotai': /\b(jotai)\b/i,
  'kibana': /\b(kibana)\b/i,
  'langchain': /\b(langchain)\b/i,
  'lightGBM': /\b(lightgbm)\b/i,
  'llamaindex': /\b(llamaindex)\b/i,
  'logstash': /\b(logstash)\b/i,
  'materialUi': /\b(material-ui)\b/i,
  'mobx': /\b(mobx|MobX)\b/i,
  'neo4j': /\b(neo4j|Neo4j)\b/i,
  'ngrx': /\b(ngrx)\b/i,
  'ngxs': /\b(ngxs)\b/i,
  'nuxt': /\b(nuxt)\b/i,
  'pinia': /\b(pinia)\b/i,
  'prefect': /\b(prefect)\b/i,
  'redux': /\b(redux)\b/i,
  'sass': /\b(sass)\b/i,
  'scala': /\b(scala)\b/i,
  'splunk': /\b(splunk)\b/i,
  'spring': /\b(spring)\b/i,
  'tecton': /\b(tecton)\b/i,
  'teradata': /\b(teradata)\b/i,
  'travisci': /\b(travis ci)\b/i,
  'uikit': /\b(uikit)\b/i,
  'vuex': /\b(vuex)\b/i,
  'xml': /\b(xml)\b/i,
  'zustand': /\b(zustand)\b/i,
  'less': /\b(less)\b/i,
  'nextjs': /\b(next.js|nextjs)\b/i,
  'remix': /\b(remix)\b/i,
  'gatsby': /\b(gatsby)\b/i,
  'antDesign': /\b(ant design)\b/i,
  'elasticsearch': /\b(elasticsearch)\b/i,
  'flux': /\b(flux)\b/i,
  'echo': /\b(echo)\b/i,
  'googleCloudFunctions': /\b(google cloud functions)\b/i,
  'pulumi': /\b(pulumi)\b/i,
  'dbt': /\b(dbt)\b/i,
  'hf': /\b(hugging face)\b/i,
} as const;

/**
 * Type for technology pattern keys
 */
export type TechnologyPatternKey = keyof typeof technologyPatterns;
